version: '3'

services:
  database:
    image: mariadb
    restart: unless-stopped
    container_name: database_users_api
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-users_api}
      MARIADB_USER: ${MARIADB_USER:-user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-pass}
      MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-yes}
    volumes:
      - ./database_data:/var/lib/mysql:rw
    ports:
      - '3307:3306'

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer_users_api
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_HOST=mariadb
      - ADMINER_DEFAULT_DB_NAME=adminer
      - ADMINER_DEFAULT_SERVER=users_api
      - ADMINER_DESIGN=nette
    ports:
      - '8002:8080'
    depends_on:
      - database
