<?php

namespace ContainerDQfIKGN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_P2BVB_9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.p2BVB.9' shared service.
     *
     * @return \App\Controller\ValidatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::update()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidatorInterface". Did you forget to add a use statement?');
    }
}
