<?php

namespace ContainerK6xxSED;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N90PJP3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N90PJP3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N90PJP3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', '.errored.EbyJvZv', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::create()": the $serializer argument is type-hinted with the non-existent class or interface: "App\\Controller\\SerializerInterface". Did you forget to add a use statement?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
