<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSWIcM8X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSWIcM8X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSWIcM8X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSWIcM8X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSWIcM8X\App_KernelDevDebugContainer([
    'container.build_hash' => 'SWIcM8X',
    'container.build_id' => '3384f2ac',
    'container.build_time' => 1680532622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSWIcM8X');
