<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbuigXE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbuigXE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWbuigXE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWbuigXE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWbuigXE\App_KernelDevDebugContainer([
    'container.build_hash' => 'WbuigXE',
    'container.build_id' => 'ce19cece',
    'container.build_time' => 1679395799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbuigXE');
