<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfHKcei\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfHKcei/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLfHKcei.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLfHKcei\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLfHKcei\App_KernelDevDebugContainer([
    'container.build_hash' => 'LfHKcei',
    'container.build_id' => '21da5c99',
    'container.build_time' => 1680263470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfHKcei');
