<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_test_index' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/']], [], [], []],
    'api_users_list' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/api/users']], [], [], []],
    'api_users_create' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/api/users']], [], [], []],
    'api_users_update' => [['user'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'user', true], ['text', '/api/users']], [], [], []],
    'api_users_delete' => [['email'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'email', true], ['text', '/api/users']], [], [], []],
    'api_users_search' => [[], ['_controller' => 'App\\Controller\\UserController::search'], [], [['text', '/api/users/search']], [], [], []],
];
